id: P01711581
initial_creation_type: input
source_metadata:
  title: Dudjom Lingpa Series
  language: nl
  description: 'We present the following texts by and about the great tertön Dudjom
    Lingpa (bdud ''joms gling pa, 1835–1904):'
  volume:
    a45a6f2162ee46c79235317699c751d1:
      title: A Sukhāvatī Prayer and Aspiration
      parent: Aspiration Prayers
    93cf8b66d6a64cc5a0f545e1bfa34edb:
      title: An Aspiration
      parent: Aspiration Prayers
    b5f020725dc74f2e84a081a814234654:
      title: An Aspiration Prayer
      parent: Aspiration Prayers
    ed19296b1d17449e90f8e8e0f434e82b:
      title: The Biography of the Great Orgyen that Naturally Liberates On Sight
      parent: Biography
    ca28e5c9dec942f7a0f7ba06d8945e1f:
      title: Golden Drink (Serkyem) and Torma Offering
      parent: Offering
    c28f92a9d1524ed1aa183de98bea1eb9:
      title: The Verse for Offering Water from the Pure Vision, An Ocean of Accomplishments
      parent: Offering
    743ab06c4ab5492f83bdb854b312aee7:
      title: A Prayer
      parent: Prayers
    a616150edeba4e25bfede81e05e3ccb4:
      title: A Prayer to Dudjom Lingpa
      parent: Prayers
    f94269f789c8496697e11143fd8b62a6:
      title: A Prayer to Padmasambhava
      parent: Prayers
    b20101e72713403493800781d6294869:
      title: A Prayer to Parṇaśavarī
      parent: Prayers
    481a2077ac3941cf8327d1d4dbc759eb:
      title: The Outer, Inner and Secret Refuge Prayer
      parent: Refuge
    d4fec9b5c9314a3db41f21f7cb519dc8:
      title: 'Making Great Bliss the Path: Visualisation and Mantra Recitation of
        Medicine Buddha'
      parent: Sādhanas
    1ac3af1e1c364bb5a888e9f6a4f90f5f:
      title: Visualization and Mantra Recitation of the Great Compassionate One
      parent: Sādhanas
created_at: '2022-02-28T23:06:52.945759'
last_modified_at: '2022-02-28T23:06:52.945762'
